### ISSUE TITLE
Migrate to flat config

### ISSUE THREAD

**Issue by zyoshoka** [misskey-dev/eslint-plugin-misskey-dev#2]
## Summary
ESLint v9.0.0 が昨日リリースされ、従来の設定方式が廃止されて flat config がデフォルトとなったのでこちらへ移行したいです。

## References
- [ESLint v9.0.0 released - ESLint - Pluggable JavaScript Linter](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/)
- [Configuration Migration Guide - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/use/configure/migration-guide)

**Comment by tamaina** [comment]
新しい記述方式、私は上手く扱えなかったので無理そう（誰かにやってほしい）

**Comment by tamaina** [comment]
Fixed by https://github.com/misskey-dev/eslint-plugin-misskey-dev/pull/3

**Comment by tamaina** [comment]
PRマージによる自動closeが効かない？

(Resolvesだとあかんのか

**Comment by tamaina** [comment]
> (Resolvesだとあかんのか

そんなことなさそう

https://docs.github.com/ja/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by tamaina** [comment]
あ、Res"lo"vesにtypoされてただけだった
